{
  'apical_utils':
  {
    'global_parameters':
    {
      'apical':
      {
        'multi_apical_possible_apical':False,
      },
    },
    'attributes':
    {
      'no_category':
      {
        'align_neuron_obj':<bound method DataInterface.align_neuron_obj of <neurd.h01_volume_utils.DataInterface object at 0x7fa9409e5e20>>,
        'unalign_neuron_obj':<bound method DataInterface.unalign_neuron_obj of <neurd.h01_volume_utils.DataInterface object at 0x7fa9409e5e20>>,
      },
    },
  },
  'axon_utils':
  {
    'global_parameters':
    {
      'auto_proof':
      {
        'skeletal_length_max_axon_spines':12000,
      },
      'axon_finding':
      {
        'axon_classification_without_synapses_excitatory':True,
        'ais_width_max':900,
        'ais_new_width_min':140,
        'min_skeletal_length':10000,
        'ais_syn_density_max_excitatory':100000,
        'ais_syn_density_max_backup_excitatory':100000,
        'ais_new_width_min_inhibitory':140,
        'n_postsyn_max':100000,
        'postsyn_distance':90000,
        'max_search_distance_addition_backup':10000,
      },
      'axon_on_dendrite':
      {
        'n_synapses_pre_min_ax_on_dendr':0,
        'synapse_pre_perc_min_ax_on_dendr':0,
        'width_max_ax_on_dendr':350,
        'dendrite_width_min_ax_on_dendr':200,
      },
      'bouton_webbing':
      {
        'max_bouton_width_to_check':120,
        'min_size_threshold_bouton':30,
        'max_size_threshold_bouton':400,
        'split_significance_threshold_web':23,
        'maximum_volume_threshold_web':3500,
        'minimum_volume_threshold_web':22,
      },
      'dendr_on_axon':
      {
        'dendrite_width_min_dendr_on_axon':250,
        'min_distance_from_soma_excitatory_dendr_on_axon':60000,
        'min_distance_from_soma_inhibitory_dendr_on_axon':10000,
        'coarse_dendrite_filter':True,
        'n_synapses_pre_min_dendr_on_axon':0,
        'min_skeletal_length_myelin':12000,
      },
    },
    'attributes':
    {
      'no_category':
      {
        'align_neuron_obj':<bound method DataInterface.align_neuron_obj of <neurd.h01_volume_utils.DataInterface object at 0x7fa9409e5e20>>,
        'unalign_neuron_obj':<bound method DataInterface.unalign_neuron_obj of <neurd.h01_volume_utils.DataInterface object at 0x7fa9409e5e20>>,
        'max_ais_distance_from_soma':50000,
      },
    },
  },
  'branch_utils':
  {
    'global_parameters':
    {
      'no_category':
      {
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'cell_type_utils':
  {
    'global_parameters':
    {
      'no_category':
      {
        'lower_width_bound_spine':300,
        'upper_width_bound_spine':800,
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'classification_utils':
  {
    'global_parameters':
    {
      'axon':
      {
        'max_spine_density_axon':8e-05,
        'max_n_spines_axon':7,
        'ais_width_axon':650,
      },
    },
    'attributes':
    {
      'no_category':
      {
        'vdi':<neurd.h01_volume_utils.DataInterface object at 0x7fa9409e5e20>,
      },
    },
  },
  'connectome_query_utils':
  {
    'global_parameters':
    {
      'no_category':
      {
      },
    },
    'attributes':
    {
      'no_category':
      {
        'vdi':<neurd.h01_volume_utils.DataInterface object at 0x7fa9409e5e20>,
      },
    },
  },
  'connectome_utils':
  {
    'global_parameters':
    {
      'no_category':
      {
      },
    },
    'attributes':
    {
      'no_category':
      {
        'vdi':<neurd.h01_volume_utils.DataInterface object at 0x7fa9409e5e20>,
      },
    },
  },
  'error_detection':
  {
    'global_parameters':
    {
      'auto_proof':
      {
        'skip_distance_poly_x':((80, 400), 'blob'),
        'skip_distance_poly_y':((1500, 1700), 'blob'),
        'use_high_degree_false_positive_filter':True,
        'width_min_high_degree_false_positive':300,
        'sibling_skeletal_angle_max_high_degree_false_positive':110,
        'width_max_low_d_match':400,
        'width_jump_axon':80,
        'double_back_threshold_double_b_dendrite':100,
        'width_max_dendr_restr':700,
        'width_max_dendr_double_back_restr':10000,
        'upstream_skeletal_length_min_dendr_restr':10000,
      },
      'high_degree_dendr':
      {
        'skip_distance_high_degree_dendr':3000,
        'width_max_high_degree_dendr':400,
        'upstream_width_max_high_degree_dendr':400,
      },
      'split':
      {
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'graph_filters':
  {
    'global_parameters':
    {
      'update':
      {
        'branch_skeletal_length_min_ax_double_b':4000,
        'branch_skeletal_length_min_double_b_axon_inh':4000,
        'comparison_distance_fork_div':800,
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'motif_utils':
  {
    'global_parameters':
    {
      'no_category':
      {
      },
    },
    'attributes':
    {
      'no_category':
      {
        'vdi':<neurd.h01_volume_utils.DataInterface object at 0x7fa9409e5e20>,
      },
    },
  },
  'neuron_geometry_utils':
  {
    'global_parameters':
    {
      'no_category':
      {
      },
    },
    'attributes':
    {
      'no_category':
      {
        'voxel_to_nm_scaling':array([ 8,  8, 33]),
        'vdi':<neurd.h01_volume_utils.DataInterface object at 0x7fa9409e5e20>,
      },
    },
  },
  'neuron_statistics':
  {
    'global_parameters':
    {
      'no_category':
      {
      },
    },
    'attributes':
    {
      'no_category':
      {
        'voxel_to_nm_scaling':array([ 8,  8, 33]),
      },
    },
  },
  'neuron_utils':
  {
    'global_parameters':
    {
      'no_category':
      {
        'skeletal_length_max_n_spines':6000,
      },
    },
    'attributes':
    {
      'no_category':
      {
        'voxel_to_nm_scaling':array([ 8,  8, 33]),
      },
    },
  },
  'preprocessing_vp2':
  {
    'global_parameters':
    {
      'axon_decomp':
      {
        'invalidation_d_axon':2500,
        'stitch_floating_axon_pieces':False,
        'combine_close_skeleton_nodes_threshold_meshparty_axon':1700,
        'max_stitch_distance_high_fid_axon':8000,
        'floating_piece_face_threshold_high_fid_axon':450,
      },
      'decomp':
      {
        'width_threshold_MAP':1000,
        'size_threshold_MAP':10000,
        'size_threshold_MAP_stitch':14000,
        'apply_expansion':True,
        'max_stitch_distance':13000,
        'max_stitch_distance_CGAL':13000,
        'use_adaptive_invalidation_d':True,
        'use_adaptive_invalidation_d_floating':True,
        'axon_width_preprocess_limb_max':350,
        'limb_remove_mesh_interior_face_threshold':150,
        'floating_piece_face_threshold':500,
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'proofreading_utils':
  {
    'global_parameters':
    {
      'auto_proof':
      {
        'width_max_high_low_degree_inh':160,
        'upstream_width_max_high_low_degree_inh':200,
        'width_max_high_high_degree_inh_dendr':650,
        'upstream_width_max_high_high_degree_inh_dendr':650,
        'dendrite_branching_filters':True,
        'dendrite_branching_filters_inh':False,
        'double_back_threshold_inh_double_b':120,
      },
      'low_branch_clusters':
      {
      },
      'split':
      {
      },
    },
    'attributes':
    {
      'no_category':
      {
        'vdi':<neurd.h01_volume_utils.DataInterface object at 0x7fa9409e5e20>,
      },
    },
  },
  'proximity_analysis_utils':
  {
    'global_parameters':
    {
      'no_category':
      {
      },
    },
    'attributes':
    {
      'no_category':
      {
        'voxel_to_nm_scaling':array([ 8,  8, 33]),
        'vdi':<neurd.h01_volume_utils.DataInterface object at 0x7fa9409e5e20>,
      },
    },
  },
  'proximity_utils':
  {
    'global_parameters':
    {
      'no_category':
      {
      },
    },
    'attributes':
    {
      'no_category':
      {
        'voxel_to_nm_scaling':array([ 8,  8, 33]),
        'vdi':<neurd.h01_volume_utils.DataInterface object at 0x7fa9409e5e20>,
      },
    },
  },
  'soma_extraction_utils':
  {
    'global_parameters':
    {
      'glia':
      {
        'glia_n_faces_threshold':3000000,
        'glia_n_faces_min':3000000,
      },
      'nuclei':
      {
      },
      'soma':
      {
        'large_mesh_threshold':40000,
        'large_mesh_threshold_inner':20000,
        'soma_size_threshold':15000,
        'soma_size_threshold_max':2000000,
        'backtrack_soma_size_threshold':15000,
        'last_size_threshold':15000,
        'second_pass_size_threshold':5000,
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'spine_utils':
  {
    'global_parameters':
    {
      'head_neck_shaft':
      {
      },
      'spine_identification':
      {
        'spine_n_face_threshold':15,
        'spine_sk_length_threshold':1000,
        'filter_by_volume_threshold':50000000,
        'clusters_threshold':5,
        'smoothness_threshold':0.08,
        'shaft_close_hole_area_top_2_mean_max':260000,
        'shaft_mesh_volume_max':600000000.0,
        'shaft_mesh_n_faces_min':10,
        'spine_volume_to_spine_area_min_bare_min':0.01,
        'spine_n_face_threshold_bare_min':10,
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'synapse_utils':
  {
    'global_parameters':
    {
      'no_category':
      {
      },
    },
    'attributes':
    {
      'no_category':
      {
        'voxel_to_nm_scaling':array([ 8,  8, 33]),
        'vdi':<neurd.h01_volume_utils.DataInterface object at 0x7fa9409e5e20>,
      },
    },
  },
}
