import numpy as np

parameters = {
  'apical_utils':
  {
    'global_parameters':
    {
      'apical':
      {
        'soma_angle_to_apical':60,
        'multi_apical_height':-460000,
        'max_upward_angle_shaft_like':30,
        'min_upward_length_shaft_like':3000,
        'min_upward_per_match_shaft_like':0.8,
        'min_upward_length_backup_shaft_like':20000,
        'min_upward_per_match_backup_shaft_like':0.5,
        'width_min_shaft_like':140,
        'min_skeletal_length_filter_apical':10000,
        'min_distance_above_soma_filter_apical':10000,
        'candidate_connected_component_radius_apical':5000,
        'multi_apical_possible_apical':True,
        'width_min_apical_high_soma':450,
        'distance_from_soma_apical_high_soma':80000,
        'min_thick_near_soma_skeletal_length_apical_high_soma':10000,
        'non_upward_skeletal_distance_upstream_buffer_filter_apical_one':-10000,
        'soma_diff_buffer_filter_apical_one':-50000,
        'downstream_vector_diff_buffer_filter_apical_one':-30000,
        'default_tie_breaker_filter_apical_one':'skeletal_length',
        'add_low_degree_apicals_off_shaft_tuft':False,
        'low_degree_apicals_min_angle_tuft':0,
        'low_degree_apicals_max_angle_tuft':40,
      },
      'oblique':
      {
        'min_angle_oblique':80,
        'max_angle_oblique':140,
        'per_match_ref_vector_min_oblique':0.8,
        'dist_match_ref_vector_min_oblique':10000,
      },
    },
    'attributes':
    {
      'no_category':
      {
        
      },
    },
  },
  'axon_utils':
  {
    'global_parameters':
    {
      'auto_proof':
      {
        'ray_trace_min_axon_spines':270,
        'ray_trace_max_axon_spines':1200,
        'skeletal_length_min_axon_spines':1000,
        'skeletal_length_max_axon_spines':6000,
        'n_synapses_pre_min_axon_spines':1,
        'n_synapses_pre_max_axon_spines':3,
        'n_faces_min_axon_spines':90,
        'downstream_upstream_dist_diff_axon_spines':1000,
        'downstream_dist_min_over_syn_axon_spines':2000,
        'exclude_starting_nodes_axon_spines':True,
        'width_min_threshold_short_thick':120,
        'skeletal_length_max_threshold_short_thick':3500,
        'ray_trace_threshold_short_thick':350,
        'parent_width_threshold_short_thick':None,
        'exclude_starting_nodes_short_thick':True,
        'add_zero_width_segments_short_thick':True,
        'width_min_threshold_parent_short_thick':95,
        'width_global_min_threshold_parent_short_thick':40,
        
      },
      'axon_finding':
      {
        'axon_soma_angle_threshold_excitatory':70,
        'ais_max_distance_from_soma_excitatory':14000,
        'axon_classification_without_synapses_excitatory':False,
        'axon_classification_without_synapses_if_no_candidate_excitatory':True,
        'ais_max_distance_from_soma_inhibitory':70000,
        'axon_soma_angle_threshold':None,
        'ais_syn_density_max':0.00015,
        'ais_syn_alternative_max':2,
        'ais_n_syn_pre_max':1,
        'ais_width_min':95,
        'ais_width_max':650,
        'max_search_distance':80000,
        'min_skeletal_length':10000,
        'n_postsyn_max':15,
        'postsyn_distance':10000,
        'ais_width_filter':True,
        'ais_new_width_min':140,
        'ais_new_width_min_inhibitory':140,
        'ais_new_width_downstream_skeletal_length':20000,
        'ais_max_distance_from_soma':None,
        'n_synapses_spine_offset_endpoint_upstream_max':3,
        'attempt_second_pass':True,
        'ais_syn_density_max_backup':0.0007,
        'ais_n_syn_pre_max_backup':100,
        'max_search_distance_addition_backup':0,
        'return_best_candidate':True,
        'best_candidate_method':'max_skeletal_length_above_threshold_and_buffer',
        'max_skeletal_length_min':50000,
        'max_skeletal_length_buffer':20000,
        'significant_lowest_density_min_skeletal_length':15000,
        'lowest_density_ratio':4,
        'downstream_distance_for_axon_angle':30000,
        'axon_classification_without_synapses_if_no_candidate':False,
        'axon_classification_without_synapses':False,
        'ais_syn_density_max_excitatory':None,
        'ais_syn_density_max_backup_excitatory':None,
        'candidate_downstream_postsyn_density_max':0.00015,
        'ais_n_syn_pre_max_inhibitory':None,
      },
      'axon_on_dendrite':
      {
        'width_max_ax_on_dendr':270,
        'n_spines_max_ax_on_dendr':10,
        'n_synapses_post_spine_max_ax_on_dendr':3,
        'n_synapses_pre_min_ax_on_dendr':1,
        'synapse_pre_perc_min_ax_on_dendr':0.6,
        'synapse_pre_perc_downstream_min_ax_on_dendr':0.9,
        'axon_skeletal_legnth_min_ax_on_dendr':2500,
        'filter_away_thin_branches_ax_on_dendr':True,
        'dendrite_width_min_ax_on_dendr':80,
        'thin_axon_skeletal_length_min_ax_on_dendr':2500,
        'thin_axon_n_synapses_post_downstream_max_ax_on_dendr':3,
        'mesh_area_min_ax_on_dendr':1,
        'closest_mesh_skeleton_dist_max_ax_on_dendr':500,
        'filter_away_myelination_myelin':True,
        'min_skeletal_length_myelin':5000,
        'max_synapse_density_myelin':7e-05,
        'max_synapse_density_pass_2_myelin':0.0001,
        'min_skeletal_length_pass_2_myelin':25000,
        'min_distance_from_soma_pass_2_myelin':-1,
        'max_width_myelin':650,
        'min_distance_from_soma_myelin':10000,
        'skeletal_length_downstream_min_ax_on_dendr':7000,
        'n_synapses_post_downstream_max_myelin':5,
      },
      'bouton_webbing':
      {
        'max_bouton_width_to_check':120,
        'min_size_threshold_bouton':27,
        'max_size_threshold_bouton':350,
        'ray_trace_threshold_bouton':200,
        'split_significance_threshold_web':20,
        'maximum_volume_threshold_web':3000,
        'minimum_volume_threshold_web':20,
      },
      'dendr_on_axon':
      {
        'min_distance_from_soma_inhibitory_dendr_on_axon':10000,
        'min_distance_from_soma_excitatory_dendr_on_axon':10000,
        'n_synapses_pre_min_dendr_on_axon':1,
        'synapse_post_perc_min_dendr_on_axon':0.6,
        'spine_density_min_dendr_on_axon':0.00012,
        'dendrite_width_min_dendr_on_axon':170,
        'dendrite_skeletal_length_min_dendr_on_axon':3000,
        'coarse_dendrite_filter':True,
        'coarse_dendrite_axon_width_min':300,
        'coarse_dendrite_synapse_post_perc_min':0.75,
        'coarse_dendrite_n_synapses_post_min':20,
        'coarse_dendrite_n_spines_min':10,
        'coarse_dendrtie_spine_density':0.00015,
        'synapse_post_perc_downstream_min_dendr_on_axon':0.9,
        'n_synapses_pre_downstream_max_dendr_on_axon':3,
        'filter_away_spiney_branches_dendr_on_axon':False,
        'n_synapses_post_spine_max_dendr_on_axon':4,
        'spine_density_max_dendr_on_axon':0.00015,
      },
    },
    'attributes':
    {
      'no_category':
      {
        'max_ais_distance_from_soma':50000,
      },
    },
  },
  'branch_utils':
  {
    'global_parameters':
    {
      'no_category':
      {
        'offset_skeleton_vector':500,
        'extra_offset_skeleton_vector':3000,
        'comparison_distance_skeleton_vector':3000,
        'offset_width_endpoint':0,
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'cell_type_utils':
  {
    'global_parameters':
    {
      'no_category':
      {
        'lower_width_bound_spine':140,
        'upper_width_bound_spine':520,
        'apply_hand_made_low_rules':False,
        'skeletal_length_processed_syn_min':15000,
        'skeletal_length_processed_spine_min':15000,
        'inhibitory_syn_density_shaft_min':0.4,
        'spine_threshold_syn_density':-1,
        'skeletal_length_threshold_syn_density':5000,
        'upper_width_bound_syn_density':10000,
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'classification_utils':
  {
    'global_parameters':
    {
      'axon':
      {
        'non_ais_width_axon':200,
        'ais_width_axon':600,
        'max_n_spines_axon':7,
        'max_spine_density_axon':8e-05,
        
        "compute_relative_attributes_every_round":False,
        "descending_axon_query":False,
        "descending_axon_y_depth_buffer":None,
        "descending_axon_skeletal_length_buffer":None,
        "descending_axon_min_axon_percentage":None,
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'connectome_query_utils':
  {
    'global_parameters':
    {
      'no_category':
      {
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'connectome_utils':
  {
    'global_parameters':
    {
      'no_category':
      {
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'error_detection':
  {
    'global_parameters':
    {
      'auto_proof':
      {
        'double_back_threshold_axon_thick_inh':135,
        'double_back_threshold_axon_thin_inh':140,
        'min_upstream_skeletal_distance':500,
        'min_distance_from_soma_for_proof':10000,
        'min_degree_to_resolve':3,
        'max_degree_to_resolve_absolute':1000,
        'max_degree_to_resolve':1000,
        'max_degree_to_resolve_wide':1000,
        'max_degree_to_resolve_width_threshold':200,
        'width_min':35,
        'width_max':170,
        'upstream_width_max':None,
        'axon_dependent':True,
        'skip_distance_poly_x':(80, 200),
        'skip_distance_poly_y':(1500, 2000),
        'offset_high_d_match':1000,
        'comparison_distance_high_d_match':2000,
        'worst_case_sk_angle_match_threshold_high_d_match':65,
        'width_diff_max_high_d_match':75,
        'width_diff_perc_high_d_match':0.6,
        'perform_synapse_filter_high_d_match':True,
        'synapse_density_diff_threshold_high_d_match':0.00015,
        'n_synapses_diff_threshold_high_d_match':6,
        'sk_angle_match_threshold_high_d_match':45,
        'sk_angle_buffer_high_d_match':25,
        'width_diff_perc_threshold_high_d_match':0.15,
        'width_diff_perc_buffer_high_d_match':0.3,
        'kiss_check_high_d_match':False,
        'kiss_check_bbox_longest_side_threshold_high_d_match':450,
        'match_method_high_d_match':'all_error_if_not_one_match',
        'use_exclusive_partner_high_d_match':True,
        'use_high_degree_false_positive_filter':True,
        'width_min_high_degree_false_positive':250,
        'sibling_skeletal_angle_max_high_degree_false_positive':110,
        'skip_distance_low_d_match':0,
        'min_upstream_skeletal_distance_low_d_match':2000,
        'min_degree_to_resolve_low_d_match':2,
        'max_degree_to_resolve_wide_low_d_match':2,
        'max_degree_to_resolve_absolute_low_d_match':2,
        'max_degree_to_resolve_low_d_match':2,
        'width_max_low_d_match':170,
        'upstream_width_max_low_d_match':None,
        'offset_low_d_match':1000,
        'comparison_distance_low_d_match':2000,
        'worst_case_sk_angle_match_threshold_low_d_match':65,
        'width_diff_max_low_d_match':75,
        'width_diff_perc_low_d_match':0.6,
        'perform_synapse_filter_low_d_match':True,
        'synapse_density_diff_threshold_low_d_match':0.00015,
        'n_synapses_diff_threshold_low_d_match':6,
        'width_max_dendr_restr':500,
        'width_max_dendr_double_back_restr':500,
        'upstream_skeletal_length_min_dendr_restr':5000,
        'upstream_skeletal_length_min_width_j_dendr':5000,
        'branch_skeletal_length_min_width_j_dendr':7000,
        'upstream_skeletal_length_min_for_min_width_j_dendr':4000,
        'width_jump_max_width_j_dendr':200,
        'upstream_skeletal_length_min_width_j_axon':5000,
        'branch_skeletal_length_min_width_j_axon':8000,
        'upstream_skeletal_length_min_for_min_width_j_axon':4000,
        'width_jump_max_width_j_axon':55,
        'axon_width_threshold_max_width_j_axon':100,
        'double_back_threshold_double_b_dendrite':120,
        'comparison_distance_double_b_dendrite':3000, #depricated
        'offset_double_b_dendrite':0, #depricated
        'branch_skeletal_length_min_double_b_dendrite':7000,
        
        'double_back_angle_func_type':"parent_skeletal_angle",
        'ignore_large_skeleton_endpoint_jump':False,
        'max_skeleton_endpoint_jump':4500,
      },
      'crossover':
      {
        'apply_width_filter':True,
        'best_match_width_diff_max':75,
        'best_match_width_diff_max_perc':0.6,
        'best_match_width_diff_min':0.25,
        'no_non_cut_disconnected_comps':True,
        'best_singular_match':True,
        'lowest_angle_sum_for_pairs':False,
      },
      'high_degree_dendr':
      {
        'skip_distance_high_degree_dendr':1200,
        'width_max_high_degree_dendr':300,
        'upstream_width_max_high_degree_dendr':300,
        'offset_high_degree_dendr':1500,
        'comparison_distance_high_degree_dendr':3000,
        'width_diff_max_high_degree_dendr':150,
        'perform_synapse_filter_high_degree_dendr':False,
        'width_diff_perc_threshold_high_d_match_dendr':0.15,
        'width_diff_perc_buffer_high_d_match_dendr':0.2,
        'use_high_degree_false_positive_filter_dendr':False,
        'min_skeletal_length_endpoints_high_degree_dendr':8000,
        'min_distance_from_soma_mesh_high_degree_dendr':7000,
      },
    },
    'attributes':
    {
      'no_category':
      {
        'double_back_threshold_axon_thick':120,
        'double_back_threshold_axon_thin':127,
      },
    },
  },
  'graph_filters':
  {
    'global_parameters':
    {
      'no_category':
      {
        'child_width_maximum_ax_web_ax_web':75,
        'parent_width_maximum_ax_web':75,
        'child_skeletal_threshold_ax_web':3000,
        'child_skeletal_threshold_total_ax_web':10000,
        'child_angle_max_ax_web':40,
        'web_size_threshold_ax_web':120,
        'web_size_type_ax_web':'ray_trace_median',
        'web_above_threshold_ax_web':True,
        'parent_width_maximum_thick_t':70,
        'min_child_width_max_thick_t':78,
        'child_skeletal_threshold_thick_t':3000,
        'child_skeletal_threshold_total_thick_t':10000,
        'child_angle_max_thick_t':40,
        'branch_skeletal_length_min_ax_double_b':2000,
        'total_downstream_skeleton_length_threshold_ax_double_b':2000,
        'upstream_skeletal_length_min_ax_double_b':5000,
        'axon_width_threshold_thin_ax_double_b':180,
        'axon_width_threshold_thick_ax_double_b':180,
        'downstream_width_max_fork_div':90,
        'upstream_width_max_fork_div':90,
        'total_downstream_skeleton_length_threshold_fork_div':4000,
        'individual_branch_length_threshold_fork_div':3000,
        'divergence_threshold_mean_fork_div':160,
        'comparison_distance_fork_div':400,
        'downstream_width_max_fork_min_dist':90,
        'upstream_width_max_fork_min_dist':145,
        'total_downstream_skeleton_length_threshold_fork_min_dist':4000,
        'individual_branch_length_threshold_fork_min_dist':4000,
        'min_distance_threshold_fork_min_dist':550,
        'upstream_width_threshold_ax_spine_at_inters':110,
        'downstream_width_threshold_ax_spine_at_inters':150,
        'child_skeletal_threshold_total_ax_spine_at_inters':10000,
        'upstream_width_threshold_min_syn_dist':110,
        'downstream_width_threshold_min_syn_dist':150,
        'min_synape_dist_min_syn_dist':1300,
        'branch_skeletal_length_min_double_b_axon_inh':2000,
        'total_downstream_skeleton_length_threshold_double_b_axon_inh':2000,
        'upstream_skeletal_length_min_double_b_axon_inh':5000,
        'axon_width_threshold_thin_double_b_axon_inh':180,
        'axon_width_threshold_thick_double_b_axon_inh':180,
        'attempt_upstream_pair_singular_double_b_axon_inh':True,
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'motif_utils':
  {
    'global_parameters':
    {
      'no_category':
      {
      },
    },
    'attributes':
    {
      'no_category':
      {
        
      },
    },
  },
  'neuron_geometry_utils':
  {
    'global_parameters':
    {
      'no_category':
      {
      },
    },
    'attributes':
    {
      'no_category':
      {
        
      },
    },
  },
  'neuron_statistics':
  {
    'global_parameters':
    {
      'no_category':
      {
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'neuron_utils':
  {
    'global_parameters':
    {
      'no_category':
      {
        'skeletal_length_max_n_spines':3000,
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'preprocess_neuron':
  {
    'global_parameters':
    {
      'axon_decomp':
      {
        'combine_close_skeleton_nodes_threshold_meshparty_axon':1300,
        'filter_end_node_length_meshparty_axon':1150,
        'filter_end_node_length_axon':1150,
        'invalidation_d_axon':1500,
        'smooth_neighborhood_axon':0,
        'meshparty_segment_size_axon':100,
        'stitch_floating_axon_pieces':True,
        'max_stitch_distance_high_fid_axon':5000,
        'floating_piece_face_threshold_high_fid_axon':50,
      },
      'decomp':
      {
        'width_threshold_MAP':500,
        'size_threshold_MAP':2000,
        'size_threshold_MAP_stitch':2000,
        'apply_expansion':False,
        'max_stitch_distance':8000,
        'max_stitch_distance_CGAL':5000,
        'filter_end_node_length':4000,
        'use_adaptive_invalidation_d':False,
        'use_adaptive_invalidation_d_floating':True,
        'axon_width_preprocess_limb_max':200,
        'limb_remove_mesh_interior_face_threshold':0,
        'surface_reconstruction_size':1000,
        'floating_piece_face_threshold':50,
        'invalidation_d':12000,
        'remove_mesh_interior_face_threshold':0,
        
        'mp_only_revised_invalidation_d':False,
        'mp_only_invalidation_d_axon_buffer':None,
        'mp_only_revised_invalidation_d_reference':None,
        'mp_only_revised_width_reference':None,
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'proofreading_utils':
  {
    'global_parameters':
    {
      'auto_proof':
      {
        'width_max_high_low_degree_inh':140,
        'upstream_width_max_high_low_degree_inh':180,
        'max_degree_to_resolve_absolute_low_degree_inh':5,
        'width_max_high_high_degree_inh_dendr':500,
        'upstream_width_max_high_high_degree_inh_dendr':500,
        'dendrite_branching_filters':False,
        'dendrite_branching_filters_inh':False,
        'double_back_threshold_inh_double_b':None,
        'use_refactored_proofread_neuron_full':False,
        'filters_dataset':"microns",
      },
      'low_branch_clusters':
      {
        'max_skeletal_length_low_branch_clusters_dendrite':8000,
        'min_n_nodes_in_cluster_low_branch_clusters_dendrite':16,
        'max_skeletal_length_low_branch_clusters_axon':8000,
        'min_n_nodes_in_cluster_low_branch_clusters_axon':16,
        'skeletal_distance_from_soma_min_axon':10000,
      },
      'red_blue':
      {
        'n_red_points_red_blue':4,
      },
      'red_blue_multi_axon_on_dendrite':
      {
        'include_one_hop_downstream_error_branches_red_blue':True,
        'one_hop_downstream_error_branches_max_distance_red_blue':1000,
        'offset_distance_for_points_valid_red_blue':1700,
        'offset_distance_for_points_error_red_blue':1000,
        'n_points_red_blue':1,
        'n_red_points_red_blue':3,
        'n_blue_points_red_blue':2,
        'red_blue_points_method_red_blue':'closest_mesh_face',
        'pair_conn_comp_by_common_upstream_red_blue':True,
        'pair_conn_comp_errors_red_blue':True,
        'group_all_conn_comp_together_red_blue':False,
        'only_outermost_branches_red_blue':True,
        'min_error_downstream_length_total_red_blue':5000,
        'split_red_blue_by_common_upstream_red_blue':True,
        'use_undirected_graph_red_blue':False,
        'avoid_one_red_or_blue_red_blue':True,
        'min_cancel_distance_absolute_red_blue':1000,
      },
      'red_blue_multi_soma':
      {
        'include_one_hop_downstream_error_branches_red_blue':True,
        'one_hop_downstream_error_branches_max_distance_red_blue':4000,
        'offset_distance_for_points_valid_red_blue':3000,
        'offset_distance_for_points_error_red_blue':3000,
        'n_points_red_blue':1,
        'n_red_points_red_blue':3,
        'n_blue_points_red_blue':2,
        'red_blue_points_method_red_blue':'closest_mesh_face',
        'pair_conn_comp_by_common_upstream_red_blue':True,
        'pair_conn_comp_errors_red_blue':True,
        'group_all_conn_comp_together_red_blue':False,
        'only_outermost_branches_red_blue':True,
        'min_error_downstream_length_total_red_blue':5000,
        'split_red_blue_by_common_upstream_red_blue':True,
        'use_undirected_graph_red_blue':False,
        'avoid_one_red_or_blue_red_blue':True,
        'min_cancel_distance_absolute_red_blue':1000,
      },
      'split':
      {
        'remove_segment_threshold':1500,
        'remove_segment_threshold_round_2':2500,
        'consider_path_neighbors_for_removal':True,
        'offset_high_degree':2000,
        'comparison_distance_high_degree':2000,
        'match_threshold_high_degree':65,
        'skip_small_soma_connectors':True,
        'small_soma_connectors_skeletal_threshold':2500,
        'double_back_threshold':80,
        'offset_double_back':1000,
        'comparison_distance_double_back':6000,
        'width_jump_threshold':200,
        'simple_path_of_2_cut':False,
        'apply_double_back_first':True,
        'double_back_threshold_at_first':110,
        'min_skeletal_length_limb':15000,
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'proximity_analysis_utils':
  {
    'global_parameters':
    {
      'no_category':
      {
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'proximity_utils':
  {
    'global_parameters':
    {
      'no_category':
      {
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'soma_extraction_utils':
  {
    'global_parameters':
    {
      'glia':
      {
        'glia_volume_threshold_in_um':2500,
        'glia_n_faces_threshold':400000,
        'glia_n_faces_min':100000,
      },
      'nuclei':
      {
        'nucleus_min':700,
        'nucleus_max':None,
      },
      'soma':
      {
        'outer_decimation_ratio':0.25,
        'large_mesh_threshold':20000,
        'large_mesh_threshold_inner':13000,
        'inner_decimation_ratio':0.25,
        'max_fail_loops':10,
        'remove_inside_pieces':True,
        'size_threshold_to_remove':1000,
        'pymeshfix_clean':False,
        'check_holes_before_pymeshfix':False,
        'second_poisson':False,
        'soma_width_threshold':0.32,
        'soma_size_threshold':9000,
        'soma_size_threshold_max':1200000,
        'volume_mulitplier':8,
        'side_length_ratio_threshold':6,
        'perform_pairing':False,
        'backtrack_soma_mesh_to_original':True,
        'backtrack_soma_size_threshold':8000,
        'poisson_backtrack_distance_threshold':None,
        'close_holes':False,
        'boundary_vertices_threshold':None,
        'last_size_threshold':2000,
        'segmentation_at_end':True,
        'largest_hole_threshold':17000,
        'second_pass_size_threshold':None,
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'spine_utils':
  {
    'global_parameters':
    {
      'head_neck_shaft':
      {
        'head_smoothness':0.09,
        'head_ray_trace_min':240,
        'head_face_min':10,
        'only_allow_one_connected_component_neck':False,
      },
      'spine_identification':
      {
        'query':'median_mesh_center > 115 and n_faces_branch>100',
        'calculate_spine_volume':True,
        'clusters_threshold':5,
        'smoothness_threshold':0.08,
        'shaft_close_hole_area_top_2_mean_max':110000,
        'shaft_mesh_volume_max':300000000.0,
        'shaft_mesh_n_faces_min':10,
        'shaft_threshold':300,
        'spine_n_face_threshold_bare_min':6,
        'spine_sk_length_threshold_bare_min':306.6,
        'filter_by_volume_threshold_bare_min':900496.186,
        'bbox_oriented_side_max_min_bare_min':300,
        'spine_volume_to_spine_area_min_bare_min':0.008,
        'sdf_mean_min_bare_min':0,
        'spine_n_face_threshold':25,
        'spine_sk_length_threshold':1000,
        'filter_by_bounding_box_longest_side_length':True,
        'side_length_threshold':5000,
        'filter_out_border_spines':False,
        'skeleton_endpoint_nullification':True,
        'skeleton_endpoint_nullification_distance':2000,
        'soma_vertex_nullification':True,
        'border_percentage_threshold':0.3,
        'check_spine_border_perc':0.4,
        'filter_by_volume':True,
        'filter_by_volume_threshold':19835293,
        'connectivity_type_for_shaft':"vertices",
        
        'filter_by_face_area_mean':False,
        'filter_by_face_area_mean_min':0,
        'filter_by_boundary_to_area_ratio':False,
        'filter_by_boundary_to_area_ratio_min':0,
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
  'synapse_utils':
  {
    'global_parameters':
    {
      'no_category':
      {
      },
    },
    'attributes':
    {
      'no_category':
      {
      },
    },
  },
}
