parameters = {
  'soma_extraction_utils':
  {
    "outer_decimation_ratio":0.25,
    "max_fail_loops":11
  },
  'spine_utils':
  {
    'global_parameters':
    {
      'head_neck_shaft':
      {
        'head_smoothness':0.09,
        'head_ray_trace_min':240,
        'head_face_min':10,
        'only_allow_one_connected_component_neck':False,
      },
      'spine_identification':
      {
        'clusters_threshold':160,
      },
    },
  },
}